---
title: "Surveys and qualitative data"
date: "2017-10-24"
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
stuff-to-add: >-
  https://www.displayr.com/alternatives-word-cloud/
  https://twitter.com/infowetrust/status/910557621693714433
  https://github.com/juliasilge/tidytext-tutorial
  https://github.com/juliasilge/tidytext-tutorial/blob/master/intro-to-tidytext.Rmd
  https://uc-r.github.io/tidy_text
  
  Accessibility - colors
  viridis + colorbrewer
  https://github.com/clauswilke/colorblindr
  
  Interactivity
  ggplotly
  
  Would be cool but no time / at BYU :)
  Calling Bullshit 6.4: Dataviz Ducks: https://www.youtube.com/watch?v=rmii1hfP6d4
  
  Rest of R4DS to get good at manipulating data
  Already ggplot experts
  Coursera
  Use it in projects! Force yourself to use it on stuff.
---

# Slides

The slides from today's lecture will go here.


# Feedback for today

First, make sure you [fill out BYU's official ratings for this class](https://studentratings.byu.edu/) sometime before Saturday, October 28.

Second, go to [this form](https://goo.gl/forms/eXleRluJZurKVltM2) and answer these questions (anonymously if you want):

1. What were the two most important things you learned in this class?
2. What were the two most exciting things you learned in this class?
3. What were the two most difficult things you had to do in this class?
4. Which class sessions were most helpful? Which were least helpful?
5. Which readings were most helpful? Which were least helpful?
6. What should I remove from future versions of this class?
7. What should I add to future versions of this class?
8. What else should I change in future versions of this class?
9. Any other comments?
